Add 1x4 layout to team cards for desktop
somethingsoftware/main-website pull request #1
Opened 2023-07-13 18:17 UTC by profilelag

2023-07-13 18:25 UTC, Mr-Bossman commented
Split the commit of binary and code. So images go in a commit before this one.

2023-07-14 00:41 UTC, Mr-Bossman requested changes

2023-07-14 01:23 UTC, profilelag commented on index.js
> +app.get('/assets/img/team4.jpeg', (req, res, next) => res.sendFile('./assets/img/team4.jpeg', {root: __dirname}));
I changed it to use express.static instead because it removes a lot that isn't needed and simplifies adding more

2023-07-14 01:33 UTC, Mr-Bossman approved these changes

2023-07-14 01:33 UTC, merged